########################################################
# k8s-ingress-claim Admission webhook registration
########################################################
# Please update the CABundle with valid CA

apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ExternalAdmissionHookConfiguration
metadata:
  name: k8s-ingress-claim
externalAdmissionHooks:
  - name: k8s-ingress-claim.yahoo.io
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ""
        apiVersions:
          - v1beta1
        resources:
          - ingresses
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: default
        name: k8s-ingress-claim
      caBundle:	
