########################################################
# k8s-ingress-claim RBAC
########################################################
# ReadOnly access for the webhook to list ingresses
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingressview
rules:
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingressview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingressview
subjects:
- kind: ServiceAccount
  name: k8s-ingress-claim
  namespace: default
