########################################################
# k8s-ingress-claim ServiceAccount
########################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: k8s-ingress-claim
  name: k8s-ingress-claim
  namespace: default
